### ISSUE TITLE
Code generation from avro

### ISSUE THREAD

**Issue by denis-yuen** [common-workflow-language/cwljava#1]
Hi, 

@pgrosu 
@tetron 

I'm going to sketch out how code generation from the CWL avro schema worked for me and then link to the code where I actually do it (and test it). Feel free to borrow/copy liberally. Manually creating the Java classes could not have been easy. Hopefully this should save some time for future me/you when migrating to draft4, etc. 

## Generating classes

The procedure for generating classes is [here](https://github.com/ga4gh/dockstore/blob/develop/README.md#cwl-avro-documents) with the important bits being:

1. Get schema salad from the common-workflow-language organization and run `python -mschema_salad --print-avro ~/common-workflow-language/draft-3/cwl-avro.yml`
This converts from yml to avro avsc. 
2. Get the avro tools jar and CWL avsc and call `java -jar avro-tools-1.7.7.jar compile schema cwl.avsc cwl` This generates Java classes.
3. Copy them to the appropriate directory in your code (you will need to insert package names)

## Using the generated classes

Note that the avro schema (avsc) as generated from yml lacks namespaces, so the generated Java classes lack package names. 

Also, you won't be able to use the avro tool classes to convert between CWL and your generated Java classes directly due to:

1. the avro tools only understand JSON and their binary format normally. Solution, use cwltool to convert from cwl to json
2. there are some quirks with the cwl files even in json form that seem to confuse the avro tool, I don't remember the details but as a result, I needed to use [gson](https://github.com/google/gson) with some customizations instead of avro out-of-the-box. 

## Examples

Example of code that you can use-reuse

[Converting from a json-representation of CWL to java objects](https://github.com/ga4gh/dockstore/blob/develop/dockstore-common/src/test/java/io/dockstore/client/cli/CWLClientTest.java)

[Directory of auto-generated classes](https://github.com/ga4gh/dockstore/tree/develop/dockstore-common/src/main/java/io/dockstore/common/cwl)

[How to configure gson to do the conversion](https://github.com/ga4gh/dockstore/tree/develop/dockstore-common/src/main/java/io/dockstore/common/cwl)

Hope that helps!

**Comment by pgrosu** [comment]
Hi Denis,

I really appreciate it for helping out with this, and am still working through the details.

Thank you,
Paul

**Comment by denis-yuen** [comment]
I've checked in the code generation process as a Travis-CI demo
(see https://travis-ci.org/common-workflow-language/cwljava ) and the resulting generated code in at https://github.com/common-workflow-language/cwljava/tree/master/WIP/alternative

**Comment by pgrosu** [comment]
Thanks :)
