### ISSUE TITLE
A small issue about abstract and method definition

### ISSUE THREAD

**Issue by pgrosu** [common-workflow-language/cwljava#12]
@tetron So I have a small dilemma.  So `InputParameter` implements `Parameter` which is an interface since it's abstract.  If I have `Parameter` as an interface, then I have to have define the set methods for `type` called `settype` with the argument of the type `RecordSchema` in `InputParameter`.  But `InputParameter` specializes `RecordSchema` to `InputRecordSchema`.  The same applies for `EnumSchema` being specialized to `InputEnumSchema`, and `ArraySchema` being specialized to `InputArraySchema`. 

The same exact thing is happening for `OutputParameter`, as above.

A similar thing is happening for `Workflow` where `OutputParameter` is specialized to `WorkflowOutputParameter`, which comes from `Process` for the field `outputs`, which is an array of `OutputParameter`.

A similar thing is happening for `CommandLineTool` where `InputParameter` is specialized to `CommandInputParameter`, which comes from `Process` for the field `inputs`, which is an array of `InputParameter`.  Also `OutputParameter` is specialized to `CommandOutputParameter`, and thus also would not be defined from `Process` for the field `outputs`, which is an array of `OutputParameter`.

So we have two options:
- [ ] Ignore the specialization restriction and define as well the methods `settype( RecordSchema ... )`, `settype( EnumSchema ... )`, `settype( ArraySchema ... )` etc., since Java will not compile it if they are undefined from an implemented interface,
- [ ] Or should Draft-3 be updated?

Thanks,
`p

**Comment by tetron** [comment]
Perhaps you could use Java generics to parameterize the interfaces?  See https://docs.oracle.com/javase/tutorial/java/generics/bounded.html

Otherwise you will need to go with option (1) and ignore the specializations.

**Comment by pgrosu** [comment]
So I use the `CWLJava` implementation to also to test the draft specifications.  The issue with multiple bounds, is that then one can have complete freedom where undefined methods just pass, and are "disconnected" from their subclasses.  Here is an example:

1) A file named `UndefinedMethods.java` containing the following:

``` Java
public interface UndefinedMethods {

    void UndefinedMethod1();
    void UndefinedMethod2();
    void UndefinedMethod3();

}
```

2) A file called `SuperClass.java` containing the following:

``` Java
public class SuperClass {

    public SuperClass() {}

    public void SuperClassMethod1() { 
        System.out.println( "I do exist!");
    }

}
```

3) A file called `SubClass.java` containing the following:

``` Java
public class SubClass {

    public void run() {
        print( new SuperClass() );
    }

    public <GenericType extends SuperClass, UndefinedMethods> void print(GenericType gt){
        System.out.println("I'm a happy running program - WHEEEEEEEE :)");
        ((SuperClass)gt).SuperClassMethod1();
  }

}
```

4) A file called `TestRun.java` containing the following, which is used for running this test:

``` Java
public class TestRun {

    public static void main( String[] args) {
        new SubClass().run();
    }
}
```

This unfortunately will compile and run without any errors:

``` Bash
$ javac TestRun.java
$
$ java TestRun
I'm a happy running program - WHEEEEEEEE :)
I do exist!
$
```

So I probably prefer to go with option (1), if I can get your blessing for this :)

Thanks,
Paul

**Comment by pgrosu** [comment]
And if I use the ampersand (&), where the type would need to be a subtype of all defined types, then in order to compile successfully I would still need to implement the methods in `UndefinedMethods.java` in `SubClass.java`, as shown below - so we're still left with option (1):

``` Java
public class SubClass extends SuperClass implements UndefinedMethods {

    public void run() {
        print( new SubClass() );
    }

    public <GenericType extends SuperClass & UndefinedMethods> void print(GenericType gt){
        System.out.println("I'm a happy running program - WHEEEEEEEE :)");
        ((SuperClass)gt).SuperClassMethod1();
  }

  public void UndefinedMethod1() {}
  public void UndefinedMethod2() {}
  public void UndefinedMethod3() {}

}
```

**Comment by pgrosu** [comment]
@tetron Not sure the parameterized types approach works as cleanly as the previous.  We would need to define inner-classes which can make testing the draft implementation too flexible for correctness:

``` Java
public interface Parameter<RecordSchema, EnumSchema, ArraySchema> { 

 RecordSchema rs = new RecordSchema();
 EnumSchema es = new EnumSchema();
 ArraySchema as = new ArraySchema();

 public static class ArraySchema { }
 public static class EnumSchema {}
 public static class RecordSchema {}

}
```
