### ISSUE TITLE
Official domain name question

### ISSUE THREAD

**Issue by pgrosu** [common-workflow-language/cwljava#14]
Hi @mr-c / @tetron 

I am putting the new version into packages, and wanted to confirm that official domain name for CWL is the following:

```
commonwl.org
```

If it is, then all packages will be under `org.commonwl`.

Thanks,
Paul

**Comment by mr-c** [comment]
Yes, that is the official domain.
Pe 21 mar. 2016 05:39, "Paul Grosu" notifications@github.com a scris:

**Comment by pgrosu** [comment]
Perfect. thanks Michael!
