### ISSUE TITLE
Step 1 (schema_salad -> UML)

### ISSUE THREAD

**Issue by pgrosu** [common-workflow-language/cwljava#19]
Hi Michael (@mr-c ),

To start the first step of the action items from here:

https://groups.google.com/forum/#!searchin/common-workflow-language/SCHEMA_salad$20uml/common-workflow-language/p0KltJPOdUU/He9eXerqIgAJ

Would an Eclipse plug-in such [ObjectAid](http://www.objectaid.com/) (demonstrated via this [YouTube video](https://www.youtube.com/watch?v=_Z3eIy5nRgQ)) with the output from CWLJava-processed schema files provide what is necessary, or is there something more I am forgetting of what would be ideal to have.

Thanks,
Paul

**Comment by mr-c** [comment]
Alas, no. We need to directly produce the UML from the schema salad model
of the specs. Perhaps you could modify your code to do that?

On Wed, Jun 8, 2016 at 12:13 AM, Paul Grosu notifications@github.com
wrote:

> Hi Michael (@mr-c https://github.com/mr-c ),
> 
> To start the first step of the action items from here:
> 
> https://groups.google.com/forum/#!searchin/common-workflow-language/SCHEMA_salad$20uml/common-workflow-language/p0KltJPOdUU/He9eXerqIgAJ
> 
> Would an Eclipse plug-in such ObjectAid http://www.objectaid.com/
> (demonstrated via this YouTube video
> https://www.youtube.com/watch?v=_Z3eIy5nRgQ) with the output from
> CWLJava-processed schema files provide what is necessary, or is there
> something more I am forgetting of what would be ideal to have.
> 
> Thanks,
> Paul
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/common-workflow-language/cwljava/issues/19, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABROCFoCb-ZP7X2lbJFPBNdy7tNAzhvMks5qJe0hgaJpZM4IwaiV
> .

## 

Michael R. Crusoe
Community Engineer & Co-founder
Common Workflow Language project
https://impactstory.org/u/0000-0002-2961-9670
michael.crusoe@gmail.com
+32 (0) 2 808 25 58
+1 480 627 9108

**Comment by pgrosu** [comment]
So there is a tool I found online called [UMLGraph](http://www.umlgraph.org/), which generates a [GraphViz](http://www.graphviz.org/) `dot` file via the command-line out of which, one would need to convert it to a `png`.  Below are the steps I performed, and the output of what it produced for CWLJava (which currently is all done through the command-line):

``` Bash
java -cp "lib\UmlGraph.jar;lib\Tools.jar" org.umlgraph.doclet.UmlGraph -private org\commonwl\lang\*.java

dot -Tpng graph.dot -o graph.png
```

Below is the UML `graph.png` generated output:

![graph](https://cloud.githubusercontent.com/assets/6555937/15901575/cbdad71e-2d71-11e6-84cf-763977db4a5b.png)

If I generate a script and include the jar files to perform this, but without the `dot` executable file from [GraphViz](http://www.graphviz.org/) to convert the `.dot` to `.png`, would this come closer to what is preferrable?

Thanks,
~p

**Comment by mr-c** [comment]
The second step is UML-> [Java, Python, ...] source code, so while a image
is nice, a UML class diagram in a format usable by a code generation tool
is better.

On Wed, Jun 8, 2016 at 6:17 PM, Paul Grosu notifications@github.com wrote:

> So there is a tool I found online called UMLGraph
> http://www.umlgraph.org/, which generates a GraphViz
> http://www.graphviz.org/ dot file via the command-line out of which,
> one would need to convert it to a png. Below are the steps I performed,
> and the output of what it produced for CWLJava (which currently is all done
> through the command-line):
> 
> java -cp "lib\UmlGraph.jar;lib\Tools.jar" org.umlgraph.doclet.UmlGraph -private org\commonwl\lang*.java
> 
> dot -Tpng graph.dot -o graph.png
> 
> Below is the UML graph.png generated output:
> 
> [image: graph]
> https://cloud.githubusercontent.com/assets/6555937/15901575/cbdad71e-2d71-11e6-84cf-763977db4a5b.png
> 
> If I generate a script and include the jar files to perform this, but
> without the dot executable file from GraphViz http://www.graphviz.org/
> to convert the .dot to .png, would this come closer to what is
> preferrable?
> 
> Thanks,
> ~p
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/common-workflow-language/cwljava/issues/19#issuecomment-224644066,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABROCPjLFzpEloDsuxMgY4c-5WTC-sXVks5qJushgaJpZM4IwaiV
> .

## 

Michael R. Crusoe
Community Engineer & Co-founder
Common Workflow Language project
https://impactstory.org/u/0000-0002-2961-9670
michael.crusoe@gmail.com
+32 (0) 2 808 25 58
+1 480 627 9108

**Comment by pgrosu** [comment]
@mr-c Sorry to reply so late, I thought I could finish it all in a day.  It's still being worked on :)

**Comment by mr-c** [comment]
No worries Paul, thanks!
Pe 17 iun. 2016 19:43, "Paul Grosu" notifications@github.com a scris:
