### ISSUE TITLE
GPL?

### ISSUE THREAD

**Issue by kellrott** [common-workflow-language/cwljava#3]
https://github.com/common-workflow-language/cwljava/blob/master/WIP/alternative/src/main/java/Utilities.java#L4

Should the whole package be under Apache, like the cwltool? It may be problematic to have portions under GPL.

**Comment by denis-yuen** [comment]
I don't feel strongly about this so if Apache is preferable, then sure.

**Comment by kellrott** [comment]
This was resolved in https://github.com/common-workflow-language/cwljava/pull/4
