### ISSUE TITLE
SchemaDefRequirement not parsed correctly

### ISSUE THREAD

**Issue by jdidion** [common-workflow-language/cwljava#30]
Two tests from the conformance suite are not parsed correctly:

* https://github.com/common-workflow-language/cwl-v1.2/blob/main/tests/record-sd-secondaryFiles.cwl
* https://github.com/common-workflow-language/cwl-v1.2/blob/main/tests/anon_enum_inside_array_inside_schemadef.cwl

These tests both contain schemaDef requirements, but the parsed object (`CommandLineToolImpl.getRequirements`) does not contains a `SchemaDefRequirementImpl`.

**Comment by mr-c** [comment]
This is due to https://github.com/common-workflow-language/schema_salad/issues/349

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-lab/cwljava/pull/32
